/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanBackTop: typeof import('vant/es')['BackTop']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanList: typeof import('vant/es')['List']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSticky: typeof import('vant/es')['Sticky']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}

// For TSX support
declare global {
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const VanBackTop: typeof import('vant/es')['BackTop']
  const VanCheckbox: typeof import('vant/es')['Checkbox']
  const VanField: typeof import('vant/es')['Field']
  const VanForm: typeof import('vant/es')['Form']
  const VanList: typeof import('vant/es')['List']
  const VanNoticeBar: typeof import('vant/es')['NoticeBar']
  const VanOverlay: typeof import('vant/es')['Overlay']
  const VanPopup: typeof import('vant/es')['Popup']
  const VanProgress: typeof import('vant/es')['Progress']
  const VanRadio: typeof import('vant/es')['Radio']
  const VanRadioGroup: typeof import('vant/es')['RadioGroup']
  const VanSticky: typeof import('vant/es')['Sticky']
  const VanTabbar: typeof import('vant/es')['Tabbar']
  const VanTabbarItem: typeof import('vant/es')['TabbarItem']
  const VanUploader: typeof import('vant/es')['Uploader']
}